// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOdjYDtgtyOnf1sZM0wZgJ8_8YkaXgnzU',
    appId: '1:996207167634:web:a34a2bab2c7ea97eb47e4b',
    messagingSenderId: '996207167634',
    projectId: 'walkmoney-1cdad',
    authDomain: 'walkmoney-1cdad.firebaseapp.com',
    storageBucket: 'walkmoney-1cdad.firebasestorage.app',
    measurementId: 'G-8LVXXK4T9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynZJAIe4GT22kx3m639s1YLSpsuPVUGg',
    appId: '1:996207167634:android:89a14406d4f2403bb47e4b',
    messagingSenderId: '996207167634',
    projectId: 'walkmoney-1cdad',
    storageBucket: 'walkmoney-1cdad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxnk6p-oDY-JEz301VQHWpHd328ptaRQ0',
    appId: '1:996207167634:ios:e9c5984137099d53b47e4b',
    messagingSenderId: '996207167634',
    projectId: 'walkmoney-1cdad',
    storageBucket: 'walkmoney-1cdad.firebasestorage.app',
    iosBundleId: 'com.parrel.walkmoney',
  );
}
